spring:
  application:
    name: test
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000



  jwt:
    secret: ${JWT_SECRET}

  springdoc:
    show-login-endpoint: true

    logging:
      level:
        org:
          hibernate:
            SQL: debug
            type: trace

  cloud:
    aws:
      s3:
        bucket: insta-clone-coding-bucket
      credentials:
        accessKey: ${S3_ACESSKEY}
        secretKey: ${S3_SECRETKEY}
      region:
        static: ap-northeast-2
        auto: false
      stack:
        auto: false