spring:
  application:
    name: instaCLone_9room

  datasource:
    url: jdbc:mysql://localhost:3306/insta?serverTimezone=Asia/Seoul
    username: root
    password: Ksy0780@

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

springdoc:
  show-login-endpoint: true
